version: '3.1'

services:
  db-supplier:
    build:
      context: .
    container_name: supplier_db
    image: supplier_db
    ports:
      - "5433:5432"
    networks:
      - local

# Rede local para comunicacao dos containers
networks:
  local:
    driver: bridge