server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ofelipedias/spring-cloud-example
          search-paths: /config-repo
          default-label: master
