server:
  port: 8081

spring:
  application:
    name: 'supplier'
  datasource:
    url: jdbc:postgresql://localhost:5433/supplier_db
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        default_schema: supplier
    hibernate:
      ddl-auto: create

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka